<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * BITÁCORA DE LECTURA — quién vio qué, no solo quién cambió qué.
 *
 * ADR-0004 y §9.L6. Es la tabla que casi ningún sistema hospitalario tiene
 * y la que decide si el hospital puede defenderse.
 *
 * El caso real dominante no es el hacker: es el empleado que abre el
 * expediente de su ex pareja, de su vecina o de un familiar. Y cuando se
 * filtra el expediente de una figura pública, sin registro de LECTURA el
 * hospital no puede identificar al responsable y responde él.
 *
 * Registrar solo escrituras deja ese riesgo completamente descubierto,
 * porque leer no modifica nada.
 *
 * ─────────────────────────────────────────────────────────────────────
 * TRES DECISIONES DE ESTRUCTURA QUE NO SE PUEDEN CAMBIAR DESPUÉS
 * ─────────────────────────────────────────────────────────────────────
 *
 * 1. PARTICIONADA POR RANGO DE FECHA, desde el día uno (§12).
 *    Proyección a 3 años: ~50M filas. Particionar una tabla de ese tamaño
 *    en caliente exige una ventana de mantenimiento, y **en un hospital no
 *    hay ventana de mantenimiento a la que apelar**. Se hace ahora, vacía,
 *    o no se hace nunca.
 *
 * 2. PARTICIÓN `DEFAULT` como red de seguridad.
 *    Sin ella, un INSERT con fecha fuera de las particiones creadas falla —
 *    y ese INSERT ocurre cuando un médico abre un expediente. **El registro
 *    de lectura nunca puede ser el motivo por el que no se puede leer un
 *    expediente a las 3 de la mañana** (§1.5). La partición default
 *    garantiza que el insert siempre entra; el comando de mantenimiento se
 *    encarga de que las mensuales existan con anticipación.
 *
 * 3. SIN `updated_at` NI `deleted_at`. Append-only de verdad.
 *    Una bitácora que se puede editar o borrar no es evidencia. Idealmente
 *    se replica además a un destino de solo escritura (§14).
 *
 * La llave primaria es COMPUESTA (id, ocurrido_en) porque PostgreSQL exige
 * que la clave de particionado forme parte de todo índice único.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE accesos_expediente (
                id                  bigint GENERATED BY DEFAULT AS IDENTITY,
                sede_id             bigint       NOT NULL,
                user_id             bigint       NOT NULL,
                paciente_id         bigint       NULL,
                recurso_tipo        varchar(255) NOT NULL,
                recurso_id          bigint       NULL,
                accion              varchar(20)  NOT NULL,
                motivo              varchar(40)  NULL,
                motivo_texto        text         NULL,
                es_break_the_glass  boolean      NOT NULL DEFAULT false,
                revisado_en         timestamptz  NULL,
                revisado_por        bigint       NULL,
                ip                  inet         NULL,
                terminal            varchar(255) NULL,
                ocurrido_en         timestamptz  NOT NULL,
                PRIMARY KEY (id, ocurrido_en)
            ) PARTITION BY RANGE (ocurrido_en)
        SQL);

        /*
         * FKs con NOT VALID: la validación escanearía la tabla entera y en
         * producción eso es un lock largo (§12, expand/contract). Acá está
         * vacía, pero el patrón se mantiene por consistencia y porque la
         * misma migración corre en la clínica que ya tiene datos.
         */
        DB::statement('ALTER TABLE accesos_expediente ADD CONSTRAINT accesos_expediente_sede_id_foreign FOREIGN KEY (sede_id) REFERENCES sedes(id)');
        DB::statement('ALTER TABLE accesos_expediente ADD CONSTRAINT accesos_expediente_user_id_foreign FOREIGN KEY (user_id) REFERENCES users(id)');

        /*
         * CHECK como defensa profunda (§12): otra aplicación, un import o
         * un script van a escribir en esta base algún día.
         *
         * Un acceso de emergencia SIN motivo escrito no es un acceso de
         * emergencia: es un acceso sin justificar. La base lo impide.
         */
        DB::statement(<<<'SQL'
            ALTER TABLE accesos_expediente
            ADD CONSTRAINT accesos_expediente_accion_check
            CHECK (accion IN ('ver', 'listar', 'buscar', 'exportar', 'imprimir'))
        SQL);

        DB::statement(<<<'SQL'
            ALTER TABLE accesos_expediente
            ADD CONSTRAINT accesos_expediente_break_the_glass_check
            CHECK (
                es_break_the_glass = false
                OR (motivo IS NOT NULL AND motivo_texto IS NOT NULL AND length(trim(motivo_texto)) >= 10)
            )
        SQL);

        // ── Índices (§12) ────────────────────────────────────────────────
        // "¿Quién vio el expediente de este paciente?" — la pregunta que
        // llega en forma de reclamo de privacidad.
        DB::statement('CREATE INDEX accesos_expediente_paciente_index ON accesos_expediente (paciente_id, ocurrido_en DESC)');

        // "¿Qué vio este empleado?" — la pregunta que llega después.
        DB::statement('CREATE INDEX accesos_expediente_usuario_index ON accesos_expediente (user_id, ocurrido_en DESC)');

        // BRIN: la tabla solo crece y se inserta en orden cronológico. Ocupa
        // kilobytes donde un btree ocuparía cientos de megas a los dos años.
        DB::statement('CREATE INDEX accesos_expediente_fecha_brin ON accesos_expediente USING brin (ocurrido_en)');

        /*
         * Índice PARCIAL para la cola de revisión del oficial de privacidad
         * (§12). Los break-the-glass sin revisar son una fracción ínfima de
         * la tabla; un índice completo sería enorme e inútil.
         */
        DB::statement(<<<'SQL'
            CREATE INDEX accesos_expediente_pendientes_revision
            ON accesos_expediente (ocurrido_en)
            WHERE es_break_the_glass = true AND revisado_en IS NULL
        SQL);

        // ── Particiones ─────────────────────────────────────────────────
        // Del inicio del año en curso hasta 12 meses adelante, más DEFAULT.
        $inicio = now()->startOfYear()->startOfMonth();

        for ($i = 0; $i < 24; $i++) {
            $desde = $inicio->copy()->addMonths($i);
            $hasta = $desde->copy()->addMonth();

            DB::statement(sprintf(
                'CREATE TABLE %s PARTITION OF accesos_expediente FOR VALUES FROM (%s) TO (%s)',
                'accesos_expediente_'.$desde->format('Y_m'),
                "'".$desde->toDateString()."'",
                "'".$hasta->toDateString()."'",
            ));
        }

        DB::statement('CREATE TABLE accesos_expediente_default PARTITION OF accesos_expediente DEFAULT');
    }

    public function down(): void
    {
        Schema::dropIfExists('accesos_expediente');
    }
};
